# Generated by Django 4.1.1 on 2022-11-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hesaplama',
            name='hesaplama_yili',
            field=models.IntegerField(default=0),
        ),
    ]
