# Generated by Django 4.1.1 on 2022-10-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sirket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sirket_adi', models.CharField(max_length=50, verbose_name='Şirket Adı')),
                ('sirket_adres', models.CharField(max_length=50, verbose_name='Şirket Adresi')),
                ('sirket_telefon', models.CharField(max_length=50, verbose_name='Şirket Telefonu')),
                ('sirket_mail', models.CharField(max_length=50, verbose_name='Şirket Mail')),
                ('sirket_website', models.CharField(max_length=50, verbose_name='Şirket Web Sitesi')),
                ('sirket_aktiflik', models.BooleanField(default=True, verbose_name='Şirket Aktiflik Durumu')),
            ],
            options={
                'verbose_name_plural': 'Şirketler',
                'permissions': [('sirket_listele', 'Şirketleri Listele')],
            },
        ),
    ]
