# Generated by Django 4.1.1 on 2022-10-27 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='perm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_muhasebe', models.BooleanField(default=False, verbose_name='Muhasebe Yetkisi')),
                ('is_mali_musavir', models.BooleanField(default=False, verbose_name='Mali Müşavir Yetkisi')),
                ('is_standart', models.BooleanField(default=False, verbose_name='Çalışan Yetkisi')),
            ],
            options={
                'verbose_name_plural': 'Yetkiler',
            },
        ),
        migrations.AlterModelOptions(
            name='sirket',
            options={'permissions': [('sirket_listele', 'Şirketleri Listele'), ('calisan_listele', 'Çalışanları Listele')], 'verbose_name_plural': 'Şirketler'},
        ),
        migrations.AddField(
            model_name='sirket',
            name='sirket_mali_musavir_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Şirket Mali Müşavir ID'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='maas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maas_tutari1', models.FloatField(default=0, verbose_name='Ocak')),
                ('maas_tutari2', models.FloatField(default=0, verbose_name='Şubat')),
                ('maas_tutari3', models.FloatField(default=0, verbose_name='Mart')),
                ('maas_tutari4', models.FloatField(default=0, verbose_name='Nisan')),
                ('maas_tutari5', models.FloatField(default=0, verbose_name='Mayıs')),
                ('maas_tutari6', models.FloatField(default=0, verbose_name='Haziran')),
                ('maas_tutari7', models.FloatField(default=0, verbose_name='Temmuz')),
                ('maas_tutari8', models.FloatField(default=0, verbose_name='Haziran')),
                ('maas_tutari9', models.FloatField(default=0, verbose_name='Eylül')),
                ('maas_tutari10', models.FloatField(default=0, verbose_name='Ekim')),
                ('maas_tutari11', models.FloatField(default=0, verbose_name='Kasım')),
                ('maas_tutari12', models.FloatField(default=0, verbose_name='Aralık')),
                ('yil', models.IntegerField(verbose_name='Yıl')),
                ('calisan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Çalışan ID')),
            ],
            options={
                'verbose_name_plural': 'Maaşlar',
            },
        ),
        migrations.CreateModel(
            name='calisan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calisan_adi', models.CharField(max_length=50, verbose_name='Çalışan Adı')),
                ('calisan_soyadi', models.CharField(max_length=50, verbose_name='Çalışan Soyadı')),
                ('calisan_telefon', models.CharField(max_length=50, verbose_name='Çalışan Telefonu')),
                ('calisan_adres', models.CharField(max_length=50, verbose_name='Çalışan Adresi')),
                ('calisan_mail', models.CharField(max_length=50, verbose_name='Çalışan Mail')),
                ('calisan_tc', models.CharField(max_length=50, verbose_name='Çalışan TC')),
                ('calisan_dogum_tarihi', models.DateField(verbose_name='Çalışan Doğum Tarihi')),
                ('calisan_ise_giris_tarihi', models.DateField(verbose_name='Çalışan İşe Giriş Tarihi')),
                ('calisan_aktiflik', models.BooleanField(default=True, verbose_name='Çalışan Aktiflik Durumu')),
                ('calisan_engelli', models.CharField(max_length=50, verbose_name='Çalışan Engelli Durumu')),
                ('calisan_tur', models.CharField(max_length=50, verbose_name='Çalışan Türü')),
                ('calisan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Çalışan ID')),
                ('calisan_sirket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calisanlar', to='user.sirket', verbose_name='Çalışan Şirket ID')),
                ('calisan_yetki_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.perm', verbose_name='Çalışan Yetki ID')),
            ],
            options={
                'verbose_name_plural': 'Çalışanlar',
            },
        ),
    ]
