# Generated by Django 4.1.1 on 2022-11-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_sirket_sirket_mali_musavir_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='calisan',
            name='calisan_emekli',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Çalışan Emekli Durumu'),
        ),
        migrations.AddField(
            model_name='calisan',
            name='calisan_indirim',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Çalışan İndirim Durumu'),
        ),
        migrations.AddField(
            model_name='calisan',
            name='calisan_tesvik',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Çalışan Tesvik Durumu'),
        ),
    ]
