# Generated by Django 4.1.1 on 2022-11-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_calisan_calisan_emekli_calisan_calisan_indirim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calisan',
            name='calisan_indirim',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Çalışan İndirim Durumu'),
        ),
    ]
