# Generated by Django 4.1.1 on 2022-11-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_calisan_calisan_indirim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calisan',
            name='calisan_emekli',
            field=models.BooleanField(default=False, null=True, verbose_name='Çalışan Emekli Durumu'),
        ),
        migrations.AlterField(
            model_name='calisan',
            name='calisan_indirim',
            field=models.BooleanField(default=False, null=True, verbose_name='Çalışan İndirim Durumu'),
        ),
    ]
