# Generated by Django 4.1.1 on 2022-11-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_calisan_calisan_emekli_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calisan',
            name='calisan_indirim',
            field=models.BooleanField(choices=[(True, 'Uygula'), (False, 'Uygulama')], default=False, null=True, verbose_name='5510/5746 İndirim Durumu'),
        ),
        migrations.AlterField(
            model_name='calisan',
            name='calisan_tesvik',
            field=models.CharField(blank=True, choices=[('pick1', 'Standart Çalışan'), ('pick2', 'Teknokent Personeli (4691)'), ('pick3', 'AR-GE Personeli (5746)'), ('pick4', '6111 Sayılı Kanun'), ('pick5', '27103 Sayılı Kanun'), ('pick6', '17103 Sayılı Kanun'), ('pick7', 'İşveren'), ('pick8', 'İşveren Teknokent Personeli'), ('pick9', 'İşveren AR-GE Personeli')], max_length=50, null=True, verbose_name='Çalışan Tesvik Durumu'),
        ),
    ]
