# Generated by Django 4.1.1 on 2022-11-22 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0008_alter_calisan_calisan_indirim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='mali_musavir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mali_musavir_adi', models.CharField(max_length=50, verbose_name='Mali Müşavir Adı')),
                ('mali_musavir_soyadi', models.CharField(max_length=50, verbose_name='Mali Müşavir Soyadı')),
                ('mali_musavir_telefon', models.CharField(max_length=50, verbose_name='Mali Müşavir Telefonu')),
                ('mali_musavir_adres', models.CharField(max_length=50, verbose_name='Mali Müşavir Adresi')),
                ('mali_musavir_mail', models.CharField(max_length=50, verbose_name='Mali Müşavir Mail')),
                ('mali_musavir_tc', models.CharField(max_length=50, verbose_name='Mali Müşavir TC')),
                ('mali_musavir_dogum_tarihi', models.DateField(verbose_name='Mali Müşavir Doğum Tarihi')),
                ('mali_musavir_ise_giris_tarihi', models.DateField(verbose_name='Mali Müşavir İşe Giriş Tarihi')),
                ('mali_musavir_aktiflik', models.BooleanField(default=True, verbose_name='Mali Müşavir Aktiflik Durumu')),
                ('mali_musavir_engelli', models.CharField(max_length=50, verbose_name='Mali Müşavir Engelli Durumu')),
                ('mali_musavir_tesvik', models.CharField(blank=True, choices=[('pick1', 'Standart Çalışan'), ('pick2', 'Teknokent Personeli (4691)'), ('pick3', 'AR-GE Personeli (5746)'), ('pick4', '6111 Sayılı Kanun'), ('pick5', '27103 Sayılı Kanun'), ('pick6', '17103 Sayılı Kanun'), ('pick7', 'İşveren'), ('pick8', 'İşveren Teknokent Personeli'), ('pick9', 'İşveren AR-GE Personeli')], max_length=50, null=True, verbose_name='Mali Müşavir Tesvik Durumu')),
                ('mali_musavir_indirim', models.BooleanField(choices=[(True, 'Uygula'), (False, 'Uygulama')], default=False, null=True, verbose_name='5510/5746 İndirim Durumu')),
                ('mali_musavir_emekli', models.BooleanField(default=False, null=True, verbose_name='Mali Müşavir Emekli Durumu')),
                ('mali_musavir_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Mali Müşavir ID')),
                ('mali_musavir_sirket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mali_musavirler', to='user.sirket', verbose_name='Mali Müşavir Şirket ID')),
            ],
            options={
                'verbose_name_plural': 'Mali Müşavirler',
            },
        ),
    ]
