# Generated by Django 4.1.1 on 2022-11-25 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_agustos_aralik_ekim_eylul_haziran_kasim_mart_mayis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maas',
            name='calisan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.calisan', verbose_name='Çalışan ID'),
        ),
    ]
