# Generated by Django 4.1.1 on 2022-11-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_bordro_agustos_arge_gun_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bordro',
            options={'verbose_name_plural': 'Bordrolar'},
        ),
        migrations.AlterField(
            model_name='bordro',
            name='agustos_vergi_dilimi',
            field=models.CharField(default=0, max_length=50, verbose_name='Ağustos Vergi Dilimi'),
        ),
        migrations.AlterField(
            model_name='bordro',
            name='aralik_vergi_dilimi',
            field=models.CharField(default=0, max_length=50, verbose_name='Aralık Vergi Dilimi'),
        ),
        migrations.AlterField(
            model_name='bordro',
            name='ekim_vergi_dilimi',
            field=models.CharField(default=0, max_length=50, verbose_name='Ekim Vergi Dilimi'),
        ),
        migrations.AlterField(
            model_name='bordro',
            name='eylul_vergi_dilimi',
            field=models.CharField(default=0, max_length=50, verbose_name='Eylül Vergi Dilimi'),
        ),
        migrations.AlterField(
            model_name='bordro',
            name='haziran_vergi_dilimi',
            field=models.CharField(default=0, max_length=50, verbose_name='Haziran Vergi Dilimi'),
        ),
        migrations.AlterField(
            model_name='bordro',
            name='kasim_vergi_dilimi',
            field=models.CharField(default=0, max_length=50, verbose_name='Kasım Vergi Dilimi'),
        ),
        migrations.AlterField(
            model_name='bordro',
            name='mart_vergi_dilimi',
            field=models.CharField(default=0, max_length=50, verbose_name='Mart Vergi Dilimi'),
        ),
        migrations.AlterField(
            model_name='bordro',
            name='mayis_vergi_dilimi',
            field=models.CharField(default=0, max_length=50, verbose_name='Mayıs Vergi Dilimi'),
        ),
        migrations.AlterField(
            model_name='bordro',
            name='nisan_vergi_dilimi',
            field=models.CharField(default=0, max_length=50, verbose_name='Nisan Vergi Dilimi'),
        ),
        migrations.AlterField(
            model_name='bordro',
            name='ocak_vergi_dilimi',
            field=models.CharField(default=0, max_length=50, verbose_name='Ocak Vergi Dilimi'),
        ),
        migrations.AlterField(
            model_name='bordro',
            name='subat_vergi_dilimi',
            field=models.CharField(default=0, max_length=50, verbose_name='Şubat Vergi Dilimi'),
        ),
        migrations.AlterField(
            model_name='bordro',
            name='temmuz_vergi_dilimi',
            field=models.CharField(default=0, max_length=50, verbose_name='Temmuz Vergi Dilimi'),
        ),
    ]
