# Generated by Django 4.1.1 on 2022-12-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_bordro_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maas',
            name='para_birimi',
            field=models.CharField(blank=True, choices=[('pick0', 'TL'), ('pick1', 'USD'), ('pick2', 'EUR')], max_length=50, null=True, verbose_name='Para Birimi'),
        ),
    ]
