# Generated by Django 4.1.1 on 2022-12-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_maas_para_birimi'),
    ]

    operations = [
        migrations.AddField(
            model_name='calisan',
            name='deneme_bitis_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Deneme Bitiş Tarihi'),
        ),
        migrations.AddField(
            model_name='calisan',
            name='deneme_suresi',
            field=models.BooleanField(default=False, null=True, verbose_name='Deneme Süresi Durumu'),
        ),
        migrations.AddField(
            model_name='mali_musavir',
            name='deneme_bitis_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Deneme Bitiş Tarihi'),
        ),
        migrations.AddField(
            model_name='mali_musavir',
            name='deneme_suresi',
            field=models.BooleanField(default=False, null=True, verbose_name='Deneme Süresi Durumu'),
        ),
    ]
