# Generated by Django 4.1.1 on 2022-12-09 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_calisan_deneme_bitis_tarihi_calisan_deneme_suresi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sube_adi', models.CharField(max_length=50, verbose_name='Şube Adı')),
                ('sube_adres', models.CharField(max_length=50, verbose_name='Şube Adresi')),
                ('sube_telefon', models.CharField(max_length=50, verbose_name='Şube Telefonu')),
                ('sube_mail', models.CharField(max_length=50, verbose_name='Şube Mail')),
                ('sube_website', models.CharField(max_length=50, verbose_name='Şube Web Sitesi')),
                ('sube_aktiflik', models.BooleanField(default=True, verbose_name='Şube Aktiflik Durumu')),
                ('sube_sirket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subeler', to='user.sirket', verbose_name='Şube Şirket ID')),
            ],
            options={
                'verbose_name_plural': 'Şubeler',
            },
        ),
        migrations.AddField(
            model_name='calisan',
            name='calisan_sube_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calisanlar', to='user.sube', verbose_name='Çalışan Şube ID'),
        ),
    ]
