# Generated by Django 4.1.1 on 2022-12-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_sube_calisan_calisan_sube_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='calisan',
            name='calisan_photo',
            field=models.ImageField(blank=True, null=True, upload_to='calisan_photo', verbose_name='Çalışan Fotoğrafı'),
        ),
    ]
