# Generated by Django 4.1.1 on 2022-12-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_calisan_calisan_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='calisan',
            name='calisan_gender',
            field=models.CharField(blank=True, choices=[('pick1', 'Erkek'), ('pick2', 'Kadın')], max_length=50, null=True, verbose_name='Çalışan Cinsiyeti'),
        ),
    ]
