# Generated by Django 4.1.1 on 2022-12-19 10:14

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_calisan_calisan_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='sirket',
            name='sirket_kisa_unvan',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Şirket Kısa Ünvanı'),
        ),
        migrations.AddField(
            model_name='sirket',
            name='sirket_kurulus_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Şirket Kuruluş Tarihi'),
        ),
        migrations.AddField(
            model_name='sirket',
            name='sirket_mersis_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Şirket Mersis Numarası'),
        ),
        migrations.AddField(
            model_name='sirket',
            name='sirket_tc_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Şirket TC Kimlik Numarası'),
        ),
        migrations.AddField(
            model_name='sirket',
            name='sirket_vergi_dairesi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Şirket Vergi Dairesi'),
        ),
        migrations.AddField(
            model_name='sirket',
            name='sirket_vergi_numarasi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Şirket Vergi Numarası'),
        ),
        migrations.AlterField(
            model_name='calisan',
            name='calisan_photo',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.get_file_path, verbose_name='Çalışan Fotoğrafı'),
        ),
    ]
