# Generated by Django 4.1.1 on 2022-12-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_sirket_sirket_kisa_unvan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='nace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nace', models.CharField(max_length=50, verbose_name='Nace Kodu')),
                ('nace_aciklama', models.CharField(max_length=50, verbose_name='Nace Açıklama')),
            ],
            options={
                'verbose_name_plural': 'Nace Kodları',
            },
        ),
    ]
