# Generated by Django 4.1.1 on 2022-12-19 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_nace'),
    ]

    operations = [
        migrations.AddField(
            model_name='sirket',
            name='sirket_nace_kodu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='user.nace', verbose_name='Şirket Nace Kodu'),
        ),
    ]
