# Generated by Django 4.1.1 on 2022-12-19 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_vergidairesi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirket',
            name='sirket_vergi_dairesi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='user.vergidairesi', verbose_name='Şirket Vergi Dairesi'),
        ),
    ]
