# Generated by Django 4.1.1 on 2022-12-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_sirket_sirket_vergi_dairesi'),
    ]

    operations = [
        migrations.AddField(
            model_name='sirket',
            name='sirket_tur',
            field=models.CharField(blank=True, choices=[('1', 'Merkez'), ('2', 'Şube'), ('3', 'Mükellefiyetsiz Şube')], max_length=50, null=True, verbose_name='Şirket Türü'),
        ),
    ]
