# Generated by Django 4.1.1 on 2022-12-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_sgkisyeri_maas_gunsayisi1_maas_gunsayisi10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maas',
            name='argegun1',
            field=models.IntegerField(default=0, verbose_name='Ocak AR-GE Gün'),
        ),
        migrations.AddField(
            model_name='maas',
            name='argegun10',
            field=models.IntegerField(default=0, verbose_name='Ekim AR-GE Gün'),
        ),
        migrations.AddField(
            model_name='maas',
            name='argegun11',
            field=models.IntegerField(default=0, verbose_name='Kasım AR-GE Gü'),
        ),
        migrations.AddField(
            model_name='maas',
            name='argegun12',
            field=models.IntegerField(default=0, verbose_name='Aralık AR-GE Gün'),
        ),
        migrations.AddField(
            model_name='maas',
            name='argegun2',
            field=models.IntegerField(default=0, verbose_name='Şubat AR-GE Gün'),
        ),
        migrations.AddField(
            model_name='maas',
            name='argegun3',
            field=models.IntegerField(default=0, verbose_name='Mart AR-GE Gün'),
        ),
        migrations.AddField(
            model_name='maas',
            name='argegun4',
            field=models.IntegerField(default=0, verbose_name='Nisan AR-GE Gün'),
        ),
        migrations.AddField(
            model_name='maas',
            name='argegun5',
            field=models.IntegerField(default=0, verbose_name='Mayıs AR-GE Gü'),
        ),
        migrations.AddField(
            model_name='maas',
            name='argegun6',
            field=models.IntegerField(default=0, verbose_name='Haziran AR-GE Gün'),
        ),
        migrations.AddField(
            model_name='maas',
            name='argegun7',
            field=models.IntegerField(default=0, verbose_name='Temmuz AR-GE Gün'),
        ),
        migrations.AddField(
            model_name='maas',
            name='argegun8',
            field=models.IntegerField(default=0, verbose_name='Ağustos AR-GE Gün'),
        ),
        migrations.AddField(
            model_name='maas',
            name='argegun9',
            field=models.IntegerField(default=0, verbose_name='Eylül AR-GE Gün'),
        ),
        migrations.AlterField(
            model_name='maas',
            name='gunsayisi1',
            field=models.IntegerField(default=0, verbose_name='Ocak Gün'),
        ),
        migrations.AlterField(
            model_name='maas',
            name='gunsayisi10',
            field=models.IntegerField(default=0, verbose_name='Ekim Gün'),
        ),
        migrations.AlterField(
            model_name='maas',
            name='gunsayisi11',
            field=models.IntegerField(default=0, verbose_name='Kasım Gün'),
        ),
        migrations.AlterField(
            model_name='maas',
            name='gunsayisi12',
            field=models.IntegerField(default=0, verbose_name='Aralıkv'),
        ),
        migrations.AlterField(
            model_name='maas',
            name='gunsayisi2',
            field=models.IntegerField(default=0, verbose_name='Şubat Gün'),
        ),
        migrations.AlterField(
            model_name='maas',
            name='gunsayisi3',
            field=models.IntegerField(default=0, verbose_name='Mart Gün'),
        ),
        migrations.AlterField(
            model_name='maas',
            name='gunsayisi4',
            field=models.IntegerField(default=0, verbose_name='Nisan Gün'),
        ),
        migrations.AlterField(
            model_name='maas',
            name='gunsayisi5',
            field=models.IntegerField(default=0, verbose_name='Mayıs Gün'),
        ),
        migrations.AlterField(
            model_name='maas',
            name='gunsayisi6',
            field=models.IntegerField(default=0, verbose_name='Haziran Gün'),
        ),
        migrations.AlterField(
            model_name='maas',
            name='gunsayisi7',
            field=models.IntegerField(default=0, verbose_name='Temmuz Gün'),
        ),
        migrations.AlterField(
            model_name='maas',
            name='gunsayisi8',
            field=models.IntegerField(default=0, verbose_name='Ağustos Gün'),
        ),
        migrations.AlterField(
            model_name='maas',
            name='gunsayisi9',
            field=models.IntegerField(default=0, verbose_name='Eylül Gün'),
        ),
        migrations.AlterField(
            model_name='maas',
            name='maas_tutari8',
            field=models.FloatField(default=0, verbose_name='Ağustos'),
        ),
    ]
