# Generated by Django 4.1.1 on 2022-12-21 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_maas_argegun1_maas_argegun10_maas_argegun11_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='mali_sirket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mali_sirket_adi', models.CharField(max_length=50, verbose_name='Mali Şirket Adı')),
                ('mali_sirket_soyadi', models.CharField(max_length=50, verbose_name='Mali Şirket Soyadı')),
                ('mali_sirket_telefon', models.CharField(max_length=50, verbose_name='Mali Şirket Telefonu')),
                ('mali_sirket_adres', models.CharField(max_length=50, verbose_name='Mali Şirket Adresi')),
                ('mali_sirket_mail', models.CharField(max_length=50, verbose_name='Mali Şirket Mail')),
            ],
        ),
        migrations.AlterField(
            model_name='calisan',
            name='calisan_emekli',
            field=models.BooleanField(choices=[(True, 'Uygula'), (False, 'Uygulama')], default=False, null=True, verbose_name='Çalışan Emekli Durumu'),
        ),
        migrations.AddField(
            model_name='mali_musavir',
            name='mali_sirket_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mali_musavirler', to='user.mali_sirket', verbose_name='Mali Şirket ID'),
        ),
    ]
