# Generated by Django 4.1.1 on 2022-12-21 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_mali_sirket_alter_calisan_calisan_emekli_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mali_sirket',
            options={'verbose_name_plural': 'Mali Şirketler'},
        ),
        migrations.RemoveField(
            model_name='mali_sirket',
            name='mali_sirket_soyadi',
        ),
    ]
