# Generated by Django 4.1.1 on 2022-12-21 08:10

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_alter_mali_sirket_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mali_musavir',
            name='mali_musavir_gender',
            field=models.CharField(blank=True, choices=[('pick1', 'Erkek'), ('pick2', 'Kadın')], max_length=50, null=True, verbose_name='Çalışan Cinsiyeti'),
        ),
        migrations.AddField(
            model_name='mali_musavir',
            name='mali_musavir_photo',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.get_file_path, verbose_name='Çalışan Fotoğrafı'),
        ),
    ]
