# Generated by Django 4.1.1 on 2022-12-21 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_mali_musavir_mali_musavir_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mali_musavir',
            name='mali_musavir_sirket_id',
        ),
    ]
