# Generated by Django 4.1.1 on 2022-12-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_remove_mali_musavir_mali_musavir_sirket_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mali_musavir',
            name='mali_musavir_id',
        ),
        migrations.AddField(
            model_name='mali_musavir',
            name='mali_musavir_id',
            field=models.ManyToManyField(to='user.sirket', verbose_name=' Bağlı Şirketler'),
        ),
    ]
