# Generated by Django 4.1.1 on 2022-12-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_remove_mali_musavir_mali_musavir_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sirket',
            name='sirket_mali_musavir_id',
        ),
        migrations.AddField(
            model_name='sirket',
            name='sirket_davet_kodu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Şirket Davet Kodu'),
        ),
    ]
