# Generated by Django 4.1.1 on 2022-12-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_remove_sirket_sirket_mali_musavir_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mali_sirket',
            name='mali_sirket_bagli_sirketler',
            field=models.ManyToManyField(blank=True, to='user.sirket', verbose_name='Mali Şirket Bağlı Şirketler'),
        ),
        migrations.AddField(
            model_name='mali_sirket',
            name='mali_sirket_davet_kodu',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mali Şirket Davet Kodu'),
        ),
    ]
