# Generated by Django 4.1.1 on 2022-12-23 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0035_mali_sirket_mali_sirket_bagli_sirketler_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mali_musavir',
            name='mali_musavir_id',
        ),
        migrations.AddField(
            model_name='mali_musavir',
            name='mali_musavir_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Mali Müşavir ID'),
            preserve_default=False,
        ),
    ]
