# Generated by Django 4.1.1 on 2022-12-23 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0037_alter_mali_musavir_mali_musavir_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calisan',
            name='calisan_emekli',
            field=models.BooleanField(choices=[(True, 'Uygula'), (False, 'Uygulama')], default=False, verbose_name='Çalışan Emekli Durumu'),
        ),
        migrations.AlterField(
            model_name='calisan',
            name='calisan_gender',
            field=models.CharField(choices=[('pick1', 'Erkek'), ('pick2', 'Kadın')], default='pick1', max_length=50, verbose_name='Çalışan Cinsiyeti'),
        ),
        migrations.AlterField(
            model_name='calisan',
            name='calisan_indirim',
            field=models.BooleanField(choices=[(True, 'Uygula'), (False, 'Uygulama')], default=False, verbose_name='5510/5746 İndirim Durumu'),
        ),
        migrations.AlterField(
            model_name='calisan',
            name='calisan_photo',
            field=models.ImageField(upload_to=user.models.get_file_path, verbose_name='Çalışan Fotoğrafı'),
        ),
        migrations.AlterField(
            model_name='calisan',
            name='calisan_sube_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calisanlar', to='user.sube', verbose_name='Çalışan Şube ID'),
        ),
        migrations.AlterField(
            model_name='calisan',
            name='calisan_tesvik',
            field=models.CharField(choices=[('pick1', 'Standart Çalışan'), ('pick2', 'Teknokent Personeli (4691)'), ('pick3', 'AR-GE Personeli (5746)'), ('pick4', '6111 Sayılı Kanun'), ('pick5', '27103 Sayılı Kanun'), ('pick6', '17103 Sayılı Kanun'), ('pick7', 'İşveren'), ('pick8', 'İşveren Teknokent Personeli'), ('pick9', 'İşveren AR-GE Personeli')], max_length=50, verbose_name='Çalışan Tesvik Durumu'),
        ),
        migrations.AlterField(
            model_name='maas',
            name='para_birimi',
            field=models.CharField(choices=[('pick0', 'TL'), ('pick1', 'USD'), ('pick2', 'EUR')], max_length=50, verbose_name='Para Birimi'),
        ),
        migrations.AlterField(
            model_name='mali_musavir',
            name='mali_musavir_emekli',
            field=models.BooleanField(default=False, verbose_name='Mali Müşavir Emekli Durumu'),
        ),
        migrations.AlterField(
            model_name='mali_musavir',
            name='mali_musavir_gender',
            field=models.CharField(choices=[('pick1', 'Erkek'), ('pick2', 'Kadın')], max_length=50, verbose_name='Çalışan Cinsiyeti'),
        ),
        migrations.AlterField(
            model_name='mali_musavir',
            name='mali_musavir_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Mali Müşavir ID'),
        ),
        migrations.AlterField(
            model_name='mali_musavir',
            name='mali_musavir_indirim',
            field=models.BooleanField(choices=[(True, 'Uygula'), (False, 'Uygulama')], default=False, verbose_name='5510/5746 İndirim Durumu'),
        ),
        migrations.AlterField(
            model_name='mali_musavir',
            name='mali_musavir_photo',
            field=models.ImageField(upload_to=user.models.get_file_path, verbose_name='Çalışan Fotoğrafı'),
        ),
        migrations.AlterField(
            model_name='mali_musavir',
            name='mali_musavir_tesvik',
            field=models.CharField(choices=[('pick1', 'Standart Çalışan'), ('pick2', 'Teknokent Personeli (4691)'), ('pick3', 'AR-GE Personeli (5746)'), ('pick4', '6111 Sayılı Kanun'), ('pick5', '27103 Sayılı Kanun'), ('pick6', '17103 Sayılı Kanun'), ('pick7', 'İşveren'), ('pick8', 'İşveren Teknokent Personeli'), ('pick9', 'İşveren AR-GE Personeli')], max_length=50, verbose_name='Mali Müşavir Tesvik Durumu'),
        ),
        migrations.AlterField(
            model_name='mali_musavir',
            name='mali_sirket_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mali_musavirler', to='user.mali_sirket', verbose_name='Mali Şirket ID'),
        ),
        migrations.AlterField(
            model_name='mali_sirket',
            name='mali_sirket_bagli_sirketler',
            field=models.ManyToManyField(to='user.sirket', verbose_name='Mali Şirket Bağlı Şirketler'),
        ),
        migrations.AlterField(
            model_name='mali_sirket',
            name='mali_sirket_davet_kodu',
            field=models.CharField(max_length=50, verbose_name='Mali Şirket Davet Kodu'),
        ),
        migrations.AlterField(
            model_name='sirket',
            name='sirket_davet_kodu',
            field=models.CharField(max_length=50, verbose_name='Şirket Davet Kodu'),
        ),
        migrations.AlterField(
            model_name='sirket',
            name='sirket_kisa_unvan',
            field=models.CharField(max_length=50, verbose_name='Şirket Kısa Ünvanı'),
        ),
        migrations.AlterField(
            model_name='sirket',
            name='sirket_kurulus_tarihi',
            field=models.DateField(verbose_name='Şirket Kuruluş Tarihi'),
        ),
        migrations.AlterField(
            model_name='sirket',
            name='sirket_mersis_no',
            field=models.CharField(max_length=50, verbose_name='Şirket Mersis Numarası'),
        ),
        migrations.AlterField(
            model_name='sirket',
            name='sirket_nace_kodu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user.nace', verbose_name='Şirket Nace Kodu'),
        ),
        migrations.AlterField(
            model_name='sirket',
            name='sirket_tc_no',
            field=models.CharField(max_length=50, verbose_name='Şirket TC Kimlik Numarası'),
        ),
        migrations.AlterField(
            model_name='sirket',
            name='sirket_tur',
            field=models.CharField(choices=[('1', 'Merkez'), ('2', 'Şube'), ('3', 'Mükellefiyetsiz Şube')], max_length=50, verbose_name='Şirket Türü'),
        ),
        migrations.AlterField(
            model_name='sirket',
            name='sirket_vergi_dairesi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user.vergidairesi', verbose_name='Şirket Vergi Dairesi'),
        ),
        migrations.AlterField(
            model_name='sirket',
            name='sirket_vergi_numarasi',
            field=models.CharField(max_length=50, verbose_name='Şirket Vergi Numarası'),
        ),
    ]
