# Generated by Django 4.1.1 on 2022-12-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_alter_calisan_calisan_emekli_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maas',
            name='ücret',
            field=models.FloatField(default=0, verbose_name='Ücret'),
        ),
    ]
