# Generated by Django 4.1.1 on 2022-12-26 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_maas_ücret'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maas',
            old_name='ücret',
            new_name='ucret',
        ),
    ]
