# Generated by Django 4.1.1 on 2023-01-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_rename_ücret_maas_ucret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bordro',
            name='agustos_kumulatif_asgari',
        ),
        migrations.RemoveField(
            model_name='bordro',
            name='agustos_kumulatif_vergi',
        ),
        migrations.RemoveField(
            model_name='bordro',
            name='aralik_kumulatif_asgari',
        ),
        migrations.RemoveField(
            model_name='bordro',
            name='aralik_kumulatif_vergi',
        ),
        migrations.RemoveField(
            model_name='bordro',
            name='ekim_kumulatif_asgari',
        ),
        migrations.RemoveField(
            model_name='bordro',
            name='ekim_kumulatif_vergi',
        ),
        migrations.RemoveField(
            model_name='bordro',
            name='eylul_kumulatif_asgari',
        ),
        migrations.RemoveField(
            model_name='bordro',
            name='eylul_kumulatif_vergi',
        ),
        migrations.RemoveField(
            model_name='bordro',
            name='haziran_kumulatif_asgari',
        ),
        migrations.RemoveField(
            model_name='bordro',
            name='haziran_kumulatif_vergi',
        ),
        migrations.RemoveField(
            model_name='bordro',
            name='kasim_kumulatif_asgari',
        ),
        migrations.RemoveField(
            model_name='bordro',
            name='kasim_kumulatif_vergi',
        ),
        migrations.RemoveField(
            model_name='bordro',
            name='mart_kumulatif_asgari',
        ),
        migrations.RemoveField(
            model_name='bordro',
            name='mart_kumulatif_vergi',
        ),
        migrations.RemoveField(
            model_name='bordro',
            name='mayis_kumulatif_asgari',
        ),
        migrations.RemoveField(
            model_name='bordro',
            name='mayis_kumulatif_vergi',
        ),
        migrations.RemoveField(
            model_name='bordro',
            name='nisan_kumulatif_asgari',
        ),
        migrations.RemoveField(
            model_name='bordro',
            name='nisan_kumulatif_vergi',
        ),
        migrations.RemoveField(
            model_name='bordro',
            name='ocak_kumulatif_asgari',
        ),
        migrations.RemoveField(
            model_name='bordro',
            name='ocak_kumulatif_vergi',
        ),
        migrations.RemoveField(
            model_name='bordro',
            name='subat_kumulatif_asgari',
        ),
        migrations.RemoveField(
            model_name='bordro',
            name='subat_kumulatif_vergi',
        ),
        migrations.RemoveField(
            model_name='bordro',
            name='temmuz_kumulatif_asgari',
        ),
        migrations.RemoveField(
            model_name='bordro',
            name='temmuz_kumulatif_vergi',
        ),
        migrations.AddField(
            model_name='bordro',
            name='bordro_kumularifasgariucret',
            field=models.FloatField(default=0, verbose_name='Bordro Kumulatif Asgari Ücret'),
        ),
        migrations.AddField(
            model_name='bordro',
            name='bordro_kumulatifasgarivergi',
            field=models.FloatField(default=0, verbose_name='Bordro Kumulatif Asgari Vergi'),
        ),
    ]
