# Generated by Django 4.1.1 on 2023-01-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_remove_bordro_agustos_kumulatif_asgari_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maas',
            name='ucrettipi',
            field=models.CharField(choices=[('pick0', 'Brüt'), ('pick1', 'Net')], default='pick0', max_length=50, verbose_name='Ücret Tipi'),
        ),
    ]
