# Generated by Django 4.1.1 on 2023-01-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_maas_ucrettipi'),
    ]

    operations = [
        migrations.AddField(
            model_name='bordro',
            name='agustos_kumulatif_asgari_vergi',
            field=models.FloatField(default=0, verbose_name='Ağustos Kumulatif Asgari Vergi'),
        ),
        migrations.AddField(
            model_name='bordro',
            name='agustos_kumulatif_vergi',
            field=models.FloatField(default=0, verbose_name='Ağustos Kumulatif Vergi'),
        ),
        migrations.AddField(
            model_name='bordro',
            name='aralik_kumulatif_asgari_vergi',
            field=models.FloatField(default=0, verbose_name='Aralık Kumulatif Asgari Vergi'),
        ),
        migrations.AddField(
            model_name='bordro',
            name='aralik_kumulatif_vergi',
            field=models.FloatField(default=0, verbose_name='Aralık Kumulatif Vergi'),
        ),
        migrations.AddField(
            model_name='bordro',
            name='ekim_kumulatif_asgari_vergi',
            field=models.FloatField(default=0, verbose_name='Ekim Kumulatif Asgari Vergi'),
        ),
        migrations.AddField(
            model_name='bordro',
            name='ekim_kumulatif_vergi',
            field=models.FloatField(default=0, verbose_name='Ekim Kumulatif Vergi'),
        ),
        migrations.AddField(
            model_name='bordro',
            name='eylul_kumulatif_asgari_vergi',
            field=models.FloatField(default=0, verbose_name='Eylül Kumulatif Asgari Vergi'),
        ),
        migrations.AddField(
            model_name='bordro',
            name='eylul_kumulatif_vergi',
            field=models.FloatField(default=0, verbose_name='Eylül Kumulatif Vergi'),
        ),
        migrations.AddField(
            model_name='bordro',
            name='haziran_kumulatif_asgari_vergi',
            field=models.FloatField(default=0, verbose_name='Haziran Kumulatif Asgari Vergi'),
        ),
        migrations.AddField(
            model_name='bordro',
            name='haziran_kumulatif_vergi',
            field=models.FloatField(default=0, verbose_name='Haziran Kumulatif Vergi'),
        ),
        migrations.AddField(
            model_name='bordro',
            name='kasim_kumulatif_asgari_vergi',
            field=models.FloatField(default=0, verbose_name='Kasım Kumulatif Asgari Vergi'),
        ),
        migrations.AddField(
            model_name='bordro',
            name='kasim_kumulatif_vergi',
            field=models.FloatField(default=0, verbose_name='Kasım Kumulatif Vergi'),
        ),
        migrations.AddField(
            model_name='bordro',
            name='mart_kumulatif_asgari_vergi',
            field=models.FloatField(default=0, verbose_name='Mart Kumulatif Asgari Vergi'),
        ),
        migrations.AddField(
            model_name='bordro',
            name='mart_kumulatif_vergi',
            field=models.FloatField(default=0, verbose_name='Mart Kumulatif Vergi'),
        ),
        migrations.AddField(
            model_name='bordro',
            name='mayis_kumulatif_asgari_vergi',
            field=models.FloatField(default=0, verbose_name='Mayıs Kumulatif Asgari Vergi'),
        ),
        migrations.AddField(
            model_name='bordro',
            name='mayis_kumulatif_vergi',
            field=models.FloatField(default=0, verbose_name='Mayıs Kumulatif Vergi'),
        ),
        migrations.AddField(
            model_name='bordro',
            name='nisan_kumulatif_asgari_vergi',
            field=models.FloatField(default=0, verbose_name='Nisan Kumulatif Asgari Vergi'),
        ),
        migrations.AddField(
            model_name='bordro',
            name='nisan_kumulatif_vergi',
            field=models.FloatField(default=0, verbose_name='Nisan Kumulatif Vergi'),
        ),
        migrations.AddField(
            model_name='bordro',
            name='ocak_kumulatif_asgari_vergi',
            field=models.FloatField(default=0, verbose_name='Ocak Kumulatif Asgari Vergi'),
        ),
        migrations.AddField(
            model_name='bordro',
            name='ocak_kumulatif_vergi',
            field=models.FloatField(default=0, verbose_name='Ocak Kumulatif Vergi'),
        ),
        migrations.AddField(
            model_name='bordro',
            name='subat_kumulatif_asgari_vergi',
            field=models.FloatField(default=0, verbose_name='Şubat Kumulatif Asgari Vergi'),
        ),
        migrations.AddField(
            model_name='bordro',
            name='subat_kumulatif_vergi',
            field=models.FloatField(default=0, verbose_name='Şubat Kumulatif Vergi'),
        ),
        migrations.AddField(
            model_name='bordro',
            name='temmuz_kumulatif_asgari_vergi',
            field=models.FloatField(default=0, verbose_name='Temmuz Kumulatif Asgari Vergi'),
        ),
        migrations.AddField(
            model_name='bordro',
            name='temmuz_kumulatif_vergi',
            field=models.FloatField(default=0, verbose_name='Temmuz Kumulatif Vergi'),
        ),
    ]
