# Generated by Django 4.1.1 on 2023-01-07 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_bordro_agustos_kumulatif_asgari_vergi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bordro',
            old_name='ocak_kumulatif_asgari_vergi',
            new_name='ocak_kumulatif_asgari_ucret',
        ),
    ]
