# Generated by Django 4.1.1 on 2023-01-07 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_rename_ocak_kumulatif_asgari_vergi_bordro_ocak_kumulatif_asgari_ucret'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bordro',
            old_name='agustos_kumulatif_asgari_vergi',
            new_name='agustos_kumulatif_asgari_ucret',
        ),
        migrations.RenameField(
            model_name='bordro',
            old_name='aralik_kumulatif_vergi',
            new_name='aralik_kumulatif_ucret',
        ),
        migrations.RenameField(
            model_name='bordro',
            old_name='ekim_kumulatif_asgari_vergi',
            new_name='ekim_kumulatif_asgari_ucret',
        ),
        migrations.RenameField(
            model_name='bordro',
            old_name='eylul_kumulatif_asgari_vergi',
            new_name='eylul_kumulatif_asgari_ucret',
        ),
        migrations.RenameField(
            model_name='bordro',
            old_name='haziran_kumulatif_asgari_vergi',
            new_name='haziran_kumulatif_asgari_ucret',
        ),
        migrations.RenameField(
            model_name='bordro',
            old_name='kasim_kumulatif_asgari_vergi',
            new_name='kasim_kumulatif_asgari_ucret',
        ),
        migrations.RenameField(
            model_name='bordro',
            old_name='mart_kumulatif_asgari_vergi',
            new_name='mart_kumulatif_asgari_ucret',
        ),
        migrations.RenameField(
            model_name='bordro',
            old_name='mayis_kumulatif_asgari_vergi',
            new_name='mayis_kumulatif_asgari_ucret',
        ),
        migrations.RenameField(
            model_name='bordro',
            old_name='nisan_kumulatif_asgari_vergi',
            new_name='nisan_kumulatif_asgari_ucret',
        ),
        migrations.RenameField(
            model_name='bordro',
            old_name='subat_kumulatif_asgari_vergi',
            new_name='subat_kumulatif_asgari_ucret',
        ),
        migrations.RenameField(
            model_name='bordro',
            old_name='temmuz_kumulatif_asgari_vergi',
            new_name='temmuz_kumulatif_asgari_ucret',
        ),
    ]
