# Generated by Django 4.1.1 on 2023-01-07 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_rename_agustos_kumulatif_asgari_vergi_bordro_agustos_kumulatif_asgari_ucret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bordro',
            name='calisan_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.calisan', verbose_name='Çalışan ID'),
        ),
    ]
