# Generated by Django 4.1.1 on 2023-01-12 08:41

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_bordro_calisan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calisan',
            name='calisan_photo',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.get_file_path, verbose_name='Çalışan Fotoğrafı'),
        ),
        migrations.AlterField(
            model_name='mali_musavir',
            name='mali_musavir_photo',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.get_file_path, verbose_name='Çalışan Fotoğrafı'),
        ),
    ]
