# Generated by Django 4.1.1 on 2023-01-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0047_alter_calisan_calisan_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bordro',
            name='agustos_kanun_no',
            field=models.CharField(default='pick1', max_length=50, verbose_name='Ağustos Kanun No'),
        ),
        migrations.AddField(
            model_name='bordro',
            name='aralik_kanun_no',
            field=models.CharField(default='pick1', max_length=50, verbose_name='Aralık Kanun No'),
        ),
        migrations.AddField(
            model_name='bordro',
            name='ekim_kanun_no',
            field=models.CharField(default='pick1', max_length=50, verbose_name='Ekim Kanun No'),
        ),
        migrations.AddField(
            model_name='bordro',
            name='eylul_kanun_no',
            field=models.CharField(default='pick1', max_length=50, verbose_name='Eylül Kanun No'),
        ),
        migrations.AddField(
            model_name='bordro',
            name='haziran_kanun_no',
            field=models.CharField(default='pick1', max_length=50, verbose_name='Haziran Kanun No'),
        ),
        migrations.AddField(
            model_name='bordro',
            name='kasim_kanun_no',
            field=models.CharField(default='pick1', max_length=50, verbose_name='Kasım Kanun No'),
        ),
        migrations.AddField(
            model_name='bordro',
            name='mart_kanun_no',
            field=models.CharField(default='pick1', max_length=50, verbose_name='Mart Kanun No'),
        ),
        migrations.AddField(
            model_name='bordro',
            name='mayis_kanun_no',
            field=models.CharField(default='pick1', max_length=50, verbose_name='Mayıs Kanun No'),
        ),
        migrations.AddField(
            model_name='bordro',
            name='nisan_kanun_no',
            field=models.CharField(default='pick1', max_length=50, verbose_name='Nisan Kanun No'),
        ),
        migrations.AddField(
            model_name='bordro',
            name='ocak_kanun_no',
            field=models.CharField(default='pick1', max_length=50, verbose_name='Ocak Kanun No'),
        ),
        migrations.AddField(
            model_name='bordro',
            name='subat_kanun_no',
            field=models.CharField(default='pick1', max_length=50, verbose_name='Şubat Kanun No'),
        ),
        migrations.AddField(
            model_name='bordro',
            name='temmuz_kanun_no',
            field=models.CharField(default='pick1', max_length=50, verbose_name='Temmuz Kanun No'),
        ),
    ]
