# Generated by Django 4.1.1 on 2023-01-19 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0048_bordro_agustos_kanun_no_bordro_aralik_kanun_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='subs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subs_sirket_adi', models.CharField(max_length=50, verbose_name='Şirket Adı')),
                ('subs_aktiflik', models.BooleanField(default=True, verbose_name='Üyelik Aktiflik Durumu')),
                ('subs_maksimum_kullanici', models.IntegerField(verbose_name='Maksimum Kullanıcı Sayısı')),
                ('subs_baslangic_tarihi', models.DateField(verbose_name='Üyelik Başlangıç Tarihi')),
                ('subs_gunsayisi', models.IntegerField(verbose_name='Üyelik Süresi (Gün)')),
            ],
        ),
        migrations.AddField(
            model_name='sirket',
            name='sirket_uyelik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='user.subs', verbose_name='Şirket Üyelik Türü'),
        ),
    ]
