# Generated by Django 4.1.1 on 2023-01-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0049_subs_sirket_sirket_uyelik'),
    ]

    operations = [
        migrations.CreateModel(
            name='maintence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintence', models.BooleanField(default=False, verbose_name='Bakım')),
            ],
            options={
                'verbose_name_plural': 'Bakım',
            },
        ),
        migrations.AlterModelOptions(
            name='subs',
            options={'verbose_name_plural': 'Üyelikler'},
        ),
    ]
