# Generated by Django 4.1.1 on 2023-01-20 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0050_maintence_alter_subs_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='maintence',
        ),
        migrations.RemoveField(
            model_name='bordro',
            name='agustos_kanun_no',
        ),
        migrations.RemoveField(
            model_name='bordro',
            name='aralik_kanun_no',
        ),
        migrations.RemoveField(
            model_name='bordro',
            name='ekim_kanun_no',
        ),
        migrations.RemoveField(
            model_name='bordro',
            name='eylul_kanun_no',
        ),
        migrations.RemoveField(
            model_name='bordro',
            name='haziran_kanun_no',
        ),
        migrations.RemoveField(
            model_name='bordro',
            name='kasim_kanun_no',
        ),
        migrations.RemoveField(
            model_name='bordro',
            name='mart_kanun_no',
        ),
        migrations.RemoveField(
            model_name='bordro',
            name='mayis_kanun_no',
        ),
        migrations.RemoveField(
            model_name='bordro',
            name='nisan_kanun_no',
        ),
        migrations.RemoveField(
            model_name='bordro',
            name='ocak_kanun_no',
        ),
        migrations.RemoveField(
            model_name='bordro',
            name='subat_kanun_no',
        ),
        migrations.RemoveField(
            model_name='bordro',
            name='temmuz_kanun_no',
        ),
        migrations.RemoveField(
            model_name='sirket',
            name='sirket_uyelik',
        ),
        migrations.DeleteModel(
            name='subs',
        ),
    ]
