# Generated by Django 4.1.1 on 2023-01-23 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0053_maintence_alter_subs_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calisan',
            name='deneme_bitis_tarihi',
        ),
        migrations.RemoveField(
            model_name='calisan',
            name='deneme_suresi',
        ),
    ]
