# Generated by Django 4.1.1 on 2023-01-24 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0054_remove_calisan_deneme_bitis_tarihi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calisan',
            name='calisan_eski_hukumlu',
            field=models.BooleanField(choices=[(True, 'Uygula'), (False, 'Uygulama')], default=False, verbose_name='Çalışan Eski Hükümlü Durumu'),
        ),
        migrations.AddField(
            model_name='calisan',
            name='calisan_iban',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Çalışan IBAN'),
        ),
        migrations.AddField(
            model_name='calisan',
            name='calisan_isten_ayrilma_nedeni',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Çalışan İşten Ayrılma Nedeni'),
        ),
        migrations.AddField(
            model_name='calisan',
            name='calisan_isten_ayrilma_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Çalışan İşten Ayrılma Tarihi'),
        ),
        migrations.AddField(
            model_name='calisan',
            name='calisan_ogrenim_durumu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Çalışan Öğrenim Durumu'),
        ),
        migrations.AddField(
            model_name='sgkisyeri',
            name='sube_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='user.sube', verbose_name='Şirket'),
        ),
        migrations.AddField(
            model_name='sube',
            name='sube_kisa_unvan',
            field=models.CharField(default=' ', max_length=50, verbose_name='Şube Kısa Ünvanı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sube',
            name='sube_kurulus_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Şube Kuruluş Tarihi'),
        ),
        migrations.AddField(
            model_name='sube',
            name='sube_mersis_no',
            field=models.CharField(default=' ', max_length=50, verbose_name='Şube Mersis Numarası'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sube',
            name='sube_nace_kodu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='user.nace', verbose_name='Şube Nace Kodu'),
        ),
        migrations.AddField(
            model_name='sube',
            name='sube_turu',
            field=models.CharField(choices=[('1', 'Merkez'), ('2', 'Şube'), ('3', 'Mükellefiyetsiz Şube')], default=' ', max_length=50, verbose_name='Şube Türü'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sube',
            name='sube_vergi_daıresi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='user.vergidairesi', verbose_name='Şube Vergi Dairesi'),
        ),
        migrations.AddField(
            model_name='sube',
            name='sube_vergi_numarasi',
            field=models.CharField(default=' ', max_length=50, verbose_name='Şube Vergi Numarası'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='iskur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iskur_no', models.CharField(max_length=50, verbose_name='İşkur Numarası')),
                ('iskur_sifre', models.CharField(max_length=50, verbose_name='İşkur Şifresi')),
                ('sube_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iskur', to='user.sube', verbose_name='Şube ID')),
            ],
        ),
    ]
