# Generated by Django 4.1.1 on 2023-01-24 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0055_calisan_calisan_eski_hukumlu_calisan_calisan_iban_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='perm',
        ),
    ]
