# Generated by Django 4.1.1 on 2023-01-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0056_delete_perm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iskur',
            name='iskur_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='İşkur Numarası'),
        ),
        migrations.AlterField(
            model_name='iskur',
            name='iskur_sifre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='İşkur Şifresi'),
        ),
        migrations.AlterField(
            model_name='sgkisyeri',
            name='sgk_isyeri_acilis_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='SGK İşyeri Açılış Tarihi'),
        ),
        migrations.AlterField(
            model_name='sgkisyeri',
            name='sgk_isyeri_adi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SGK İşyeri Adı'),
        ),
        migrations.AlterField(
            model_name='sgkisyeri',
            name='sgk_isyeri_adres_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SGK İşyeri Adres Numarası'),
        ),
        migrations.AlterField(
            model_name='sgkisyeri',
            name='sgk_isyeri_kodu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SGK İşyeri Kodu'),
        ),
        migrations.AlterField(
            model_name='sgkisyeri',
            name='sgk_isyeri_mulk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SGK İşyeri Mülkiyeti'),
        ),
        migrations.AlterField(
            model_name='sgkisyeri',
            name='sgk_isyeri_sicil_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SGK İşyeri Sicil Numarası'),
        ),
        migrations.AlterField(
            model_name='sgkisyeri',
            name='sgk_isyeri_sifre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SGK İşyeri Şifresi'),
        ),
        migrations.AlterField(
            model_name='sube',
            name='sube_adi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Şube Adı'),
        ),
        migrations.AlterField(
            model_name='sube',
            name='sube_adres',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Şube Adresi'),
        ),
        migrations.AlterField(
            model_name='sube',
            name='sube_kisa_unvan',
            field=models.CharField(max_length=50, verbose_name='Şube Kısa Ünvanı, null=True,blank=True)'),
        ),
        migrations.AlterField(
            model_name='sube',
            name='sube_mail',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Şube Mail'),
        ),
        migrations.AlterField(
            model_name='sube',
            name='sube_telefon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Şube Telefonu'),
        ),
        migrations.AlterField(
            model_name='sube',
            name='sube_website',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Şube Web Sitesi'),
        ),
    ]
