# Generated by Django 4.1.1 on 2023-01-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0058_rename_sube_vergi_daıresi_sube_sube_vergi_dairesi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sube',
            name='sube_kisa_unvan',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Şube Kısa Ünvanı'),
        ),
        migrations.AlterField(
            model_name='sube',
            name='sube_turu',
            field=models.CharField(blank=True, choices=[('1', 'Merkez'), ('2', 'Şube'), ('3', 'Mükellefiyetsiz Şube')], max_length=50, null=True, verbose_name='Şube Türü'),
        ),
        migrations.AlterField(
            model_name='sube',
            name='sube_vergi_numarasi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Şube Vergi Numarası'),
        ),
    ]
