# Generated by Django 4.1.1 on 2023-01-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0059_alter_sube_sube_kisa_unvan_alter_sube_sube_turu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sube',
            name='sube_mersis_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Şube Mersis Numarası'),
        ),
    ]
