# Generated by Django 4.1.1 on 2023-01-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0060_alter_sube_sube_mersis_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maas',
            name='para_birimi',
            field=models.CharField(choices=[('pick0', 'TL'), ('pick1', 'USD'), ('pick2', 'EUR')], default='pick0', max_length=50, verbose_name='Para Birimi'),
        ),
    ]
