# Generated by Django 4.1.1 on 2023-02-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0061_alter_maas_para_birimi'),
    ]

    operations = [
        migrations.AddField(
            model_name='calisan',
            name='calisan_isten_ayrilma',
            field=models.BooleanField(default=False, verbose_name='Çalışan İşten Ayrıldı'),
        ),
        migrations.AlterField(
            model_name='calisan',
            name='calisan_isten_ayrilma_nedeni',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Çalışan İşten Ayrılma Nedeni'),
        ),
    ]
