# Generated by Django 4.1.1 on 2023-02-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0062_calisan_calisan_isten_ayrilma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calisan',
            name='calisan_isten_ayrilma_kodu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Çalışan İşten Ayrılma Kodu'),
        ),
    ]
